ruby/jumpstartlab/blogger/config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :tags
end

ruby/jumpstartlab/blogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/jumpstartlab/blogger/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect { |s| s.strip.downcase }.uniq
    self.tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  end
end

ruby/jumpstartlab/blogger/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

ruby/jumpstartlab/blogger/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

ruby/jumpstartlab/blogger/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

ruby/jumpstartlab/blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby/jumpstartlab/blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
#    @article = Article.new(params[:article])
#    @article = Article.new(title: params[:article][:title],
#                           body: params[:article][:body])
#    @article.title = params[:article][:title]
#    @article.body = params[:article][:body]
    @article.save

    flash.notice = "Article #{@article.title} created!"

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article #{@article.title} deleted!"

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article #{@article.title} updated!"

    redirect_to article_path(@article)
  end
end

ruby/jumpstartlab/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

ruby/jumpstartlab/blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    flash.notice = "Tag #{@tag.name} deleted!"

    redirect_to tags_path
  end
end

ruby/jumpstartlab/blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/jumpstartlab/blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

ruby/jumpstartlab/blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/jumpstartlab/blogger/app/helpers/tags_helper.rb
module TagsHelper
end

ruby/jumpstartlab/blogger/app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

ruby/jumpstartlab/blogger/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
    <%= f.label :tag_list %><br />
		<%= f.text_area :tag_list %>
  <p>
	</p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

ruby/jumpstartlab/blogger/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render partial: 'form' %>

ruby/jumpstartlab/blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
<!--      <%= article.title %> -->
      <%= link_to article.title, article_path(article), class: 'article.title', id: "article_#{article.id}" %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new Article", new_article_path, class: 'new_article' %>

ruby/jumpstartlab/blogger/app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<%= render partial: 'form' %>

ruby/jumpstartlab/blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<h3>Comments <%= @article.comments.size %> </h3>
<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Back", articles_path %>

ruby/jumpstartlab/blogger/app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, 'Your name' %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, 'Your comment' %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

ruby/jumpstartlab/blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>

    <%= yield %>
  </body>
</html>

ruby/jumpstartlab/blogger/app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag), class: 'tag.title', id: "tag_#{tag.id}" %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create a tag', new_tag_path, class: 'new_tag' %>

ruby/jumpstartlab/blogger/app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<%= link_to "Delete", tag_path(@tag), method: :delete, data: {confirm: "Are you sure?"} %>